config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('post/', include('post.urls', namespace='post')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.apps import PostConfig
from post.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = PostConfig.name
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('view/<int:pk>', PostDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete')
]

post/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='post/', verbose_name='изображение', **NULLABLE)
    create_date = models.DateField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    is_public = models.BooleanField(default=True, verbose_name='опубликован')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

post/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from post.models import Post


class PostCreateView(CreateView):
    model = Post
    fields = ('title', 'body', 'image', 'is_public')
    success_url = reverse_lazy('post:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_public=True)
        return queryset

class PostDetailView(DetailView):
    model = Post
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count +=1
        self.object.save()
        return self.object

class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'body', 'image', 'is_public')
   # success_url = reverse_lazy('post:list')
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('post:view',args=[self.kwargs.get('pk')])
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('post:list')
    slug_field = 'pk'
    slug_url_kwarg = 'pk'

post/templates/post/post_confirm_delete.html
{% extends 'catalog/base.html' %}

    {% block content %}
        <div class="row" xmlns="http://www.w3.org/1999/html">
          <div class="col-12">
            <div class="card">
                 <div class="card-body">
                     <form method="POST">
                     {% csrf_token %}
                         <p>Удалить статью "{{ object.title }}"?</p>
                         <button type="submit" class="btn btn-danger">Подтвердить</button>
                         <a href="{% url 'post:list' %}" class="btn btn-success">Отменить</a>
                     </form>

                </div>
            </div>
          </div>
        </div>
    {% endblock %}

post/templates/post/post_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  <div class="col">
"{{ object.title }}" ({{ object.slug }})
    <div class="card shadow-sm">
            <img class="card-img-top"
                 data-crs = "{{ object.post|media }}"
                 alt="Card image cap">
            <div class="card-body">
              <p class="card-text">{{ object.body }}</p>
              <p class="card-text">{{ object.create_date }}</p>
              <p class="card-text">Просмотры: {{ object.views_count }}</p>
                 <div class="d-flex justify-content-between align-items-center">
                         </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
  </div>
</div>
{% endblock %}

post/templates/post/post_form.html
{% extends 'catalog/base.html' %}

    {% block content %}
        <div class="row">
          <div class="col-12">
            <div class="card">
                 <div class="card-body">
                     <form method="post">
                     {% csrf_token %}
                     {{ form.as_p }}
                  <button type="submit" class="btn btn-success">
                      {% if object %}
                      Сохранить
                      {% else %}
                      Создать</button>
                      {% endif %}
                     </form>

                </div>
            </div>
          </div>
        </div>
    {% endblock %}

post/templates/post/post_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<a  class="btn btn-sm btn-outline-success" href="{% url 'post:create' %}">Добавить статью</a>
<p></p>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
             <div class="card-body">
              <p class="card-text">{{ object.title }}</p>
                 <p class="card-text">{{ object.body|slice:150 }}</p>
                 <p class="card-text">{{ object.create_date}}</p>
                 <p class="card-text">{{ object.views_count }}</p>
                   <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a <button type="button" class="btn btn btn-outline-success" href="{% url 'post:view' object.pk %}">Прочитать</button></a>
                <a <button type="button" class="btn btn-sm btn-outline-warning" href="{% url 'post:edit' object.pk %}">Редактировать</button></a>
                <a <button type="button" class="btn btn-sm btn-outline-danger" href="{% url 'post:delete' object.pk %}">Удалить</button></a>
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
  </div>
      {% endblock %}