config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('post/', include('post.urls', namespace='post')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.apps import PostConfig
from post.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = PostConfig.name
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('view/<int:pk>', PostDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmedView, \
    EmailConfirmetionFailedView, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email_confirmation_sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<uidb64>/<token>', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm_email_failed/', EmailConfirmetionFailedView.as_view(), name='confirm_email_failed'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    phone = models.CharField(max_length=20,verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    email_verify = models.BooleanField(default=False, verbose_name='верификация email')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from urllib import request

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        #self.object = form.save()
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain
        send_mail(
            'Регистрация на платформе.',
            f'Для завершения регистации перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list= [user.email],
            fail_silently=False,
        )
        return redirect('users:email_confirmation_sent')

class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:confirm_email_failed')

class EmailConfirmationSentView(TemplateView):
    template_name = 'users/confirm_email_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо для подтверждения электронного адреса отправлено. Перейдите в свою электронную почту, указанную при регистрациию'
        return context

class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес подтвержден'
        return context

class EmailConfirmetionFailedView(TemplateView):
    template_name = 'users/confirm_email_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не подтвержден'
        return context

class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('users:login'))

users/templates/users/confirm_email.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <p>Проверьте почту, чтобы завершить регистрацию.</p>
 </div>

{% endblock %}

users/templates/users/confirm_email_failed.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <p>Ошибка подтверждения</p>
          <p>Ссылка для подтверждения недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
 </div>

{% endblock %}

users/templates/users/confirm_email_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <p>Письмо подтверждения отправлено!</p>
          <p>На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и пройдите по ссылке, чтобы завершить регистрацию.</p>
 </div>

{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <p>Электронная почта подтверждена</p>
          <p>Ваш адрес электронной почты успешно подтвержден. Благодарим за регистрацию!</p>
 </div>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="col-3"></div>
             <div class="card col-6">
               <div class="card-header">
                   <h3 class="card-title">
                     Вход
                   </h3>
                      <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                           <button type="submit" class="btn btn-success">Войти</button>
                      </div>
                   </div>
               </div>
         </form>
   </div>
 </div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="col-3"></div>
             <div class="card col-6">
               <div class="card-header">
                   <h3 class="card-title">
                     Регистрация
                   </h3>
                      <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                           <button type="submit" class="btn btn-success">Регистрация</button>
                      </div>
                   </div>
               </div>
         </form>
   </div>
 </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
          <div class="col-3"></div>
             <div class="card col-6">
               <div class="card-header">
                   <h3 class="card-title">
                     Профиль
                   </h3>
                      <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                           <button type="submit" class="btn btn-success">Сохранить</button>
                           <br>
                          <br>
                           <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
                           </br>
                      </div>
                   </div>
               </form>
    </div>
 </div>

{% endblock %}