catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, category, ProductListView, ProductDetailView, CategoryListView, ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name


urlpatterns = [
    path('',ProductListView.as_view() , name='home'),
    path('contacts/', contacts),
    path('category/', CategoryListView.as_view(), name='category'),
    path('<slug:id>/product/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('post/', include('post.urls', namespace='post')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.apps import PostConfig
from post.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = PostConfig.name
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('view/<int:pk>', PostDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete')
]

catalog/models.py
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from config import settings

NULLABLE = {'blank': True, 'null': True}
class Product(models.Model):
    product_name = models.CharField(max_length=180, verbose_name='название продукта')
    description_prod = models.TextField(verbose_name='описание', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    picture = models.ImageField(upload_to='catalog/',verbose_name='изображение', **NULLABLE)
    purchase_price = models.FloatField(verbose_name='стоимость покупки', **NULLABLE)
    date_creation =models.DateField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    date_change = models.DateField(auto_now_add=True, verbose_name='дата изменения', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.product_name};\n' \
               f'Описание: {self.description_prod}\n' \
               f'Цена: {self.purchase_price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('product_name',)

    permissions = [
        (
            'set_is_published',
            'Can published'
        ),
        (
            'set_description_prod',
            'Can description'
        ),
        (
            'set_category',
            'Can category_product'
        )

    ]

class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='название категории')
    description_cat = models.TextField(verbose_name='описание', **NULLABLE)
  #  create_at = models.CharField(max_length=10, **NULLABLE)

    def __str__(self):
        return f'{self.id}: {self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('category_name',)
class Version(models.Model):

    VERSION = [(True, 'активная'), (False, 'не активная'),]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.CharField(max_length=5, verbose_name='номер версии', **NULLABLE)
    name = models.CharField(max_length=50, verbose_name='название версии', **NULLABLE)
    is_active = models.BooleanField(choices=VERSION, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product} {self.number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('number',)


@receiver(post_save, sender=Version)
def set_current_version(sender, instance, **kwargs):
    if instance.is_active:
        Version.objects.filter(product=instance.product).exclude(pk=instance.pk).update(is_active=False)

catalog/forms.py
from django import forms

from catalog.models import Product, Version

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
class ProductForm(StyleFormMixin, forms.ModelForm, ):

    class Meta:
        model = Product
        exclude = ('owner',)

    def get_form(self, request, obj=None, **kwargs):
        form = super().get_form(request, obj, **kwargs)
        is_staff = request.user.is_staff
        if is_staff:
            form.base_fields['product_name'].disabled = True
            form.base_fields['purchase_price'].disabled = True
            form.base_fields['owner'].disabled = True
            return form

    def clean_product_name(self):
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        cleaned_data = self.cleaned_data['product_name']

        for item in words:
            if item in cleaned_data.lower():
                raise forms.ValidationError(f'"{item}" запрещено, выберите другое')

        return cleaned_data

    def clean_description_prod(self):
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        cleaned_data = self.cleaned_data['description_prod']

        for word in words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'"{word}" запрещено, выберите другое')

        return cleaned_data

class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.shortcuts import render, redirect
from catalog.models import Product, Category, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from catalog.forms import ProductForm, VersionForm
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
#from django.http import Http404
from django.contrib.auth.mixins import PermissionRequiredMixin
#from django.utils.decorators import method_decorator
#from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import UserRequiredMixin
from catalog.servises import get_cache_category_list


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    login_url = 'catalog:home'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UserRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    login_url = 'catalog:home'
    success_message = 'Успешно изменено'
    permission_required = 'catalog.change_product'

    def get_form_class(self):
        return super().get_form_class()

    def get_context_data(self, **kwargs):

        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST,instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Новое сообщение от {name}({phone}): {message}')
    return render(request, 'catalog/contacts.html')



class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'

#def home(request):
  #  product_list = Product.objects.all()
  #  content = {'object_list': product_list}
  #  return render(request, 'catalog/home.html', content)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        for object in context['product_list']:
            active_version = Version.objects.filter(product=object, is_active=True).last()
            if active_version:
                object.active_version_number = active_version.number
            else:
                object.active_version_number = None
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'
#def product(request, id):
 #  object = Product.objects.get(pk=id)
  # content = {'object': object}
   #return render(request, 'catalog/product.html', content)

class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category'] = get_cache_category_list()
        return context_data
def category(request):
    content = {
        'category_list': Category.objects.all(),
        'title': 'Категории товаров'
    }
    return render(request, 'catalog/category.html', content)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>


    <title>Техника для дома</title>


<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/imazin.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


  </head>
  <body>
  {% include 'catalog/includes/inc_main_menu.html'%}


<header data-bs-theme="dark">


  </div>
</header>

<main>

  <section class="py-5 text-center container">

  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Наверх</a>
    </p>
    <p class="mb-1">Техника для дома</p>
    <p class="mb-0"> <a href="/">Главная</a></p>
    <p class="mb-0"> <a href="/contacts">Контакты</a></p>
    <p class="mb-0"> <a href="{% url 'post:list' %}">Статьи</a></p>
    <p class="mb-1">&copy; 2023 - {% now 'Y' %}</p>
  </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"</script>

    </body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for category in category_list %}
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Изображение</text></svg>
            <div class="card-body">
              <p class="card-text">Категория: {{ category.category_name }}</p>
              <p class="card-text">Описание: {{ category.description_cat }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a <button type="button" class="btn btn-sm btn-outline-secondary" href="/product/{{object.pk}}">Просмотр товар</button></a>
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}

    </div>
      {% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                    </form>
                    <input type="submit" value="Отправить">
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
{% if user.is_authenticated %}
<a  class="btn btn-sm btn-outline-success" href="{% url 'catalog:create_product' %}">Добавить товар</a>
{% endif %}
<p></p>
{% include 'catalog/includes//messages.html' %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% if user.is_staff %}
    {% for object in object_list %}
    <div class="col">
          <div class="card shadow-sm">
            <img class="card-img-top"
                 crs = "{{ object.picture|media }}"
                 alt="Card image cap"/>
            <div class="card-body">
              <p class="card-text">Товар: {{ object.product_name }}</p>
              <p class="card-text">Описание: {{ object.description_prod|slice:100}}</p>
              <p class="card-text">Цена: {{ object.purchase_price }} руб.</p>
              <p class="card-text">Опубликовано: {% if object.is_published == True %} <p>Да</p> {% else %} <p>Нет</p> {% endif %}
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Купить</button>
                 <a <button type="button" class="btn btn-sm btn-outline-success" href="{% url 'catalog:product' object.pk %}">Просмотр товара</button></a>
                    {% if perms.catalog.change_product and user == object.owner %}
                    <a <button type="button" class="btn btn-sm btn-outline-info" href="{% url 'catalog:update_product' object.pk %}">Изменить</button></a>
                    {% endif %}
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
    {% endfor%}
     {% else %}
        {% for object in object_list %}
         {% if object.is_published %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="card-img-top"
                 crs = "{{ object.picture|media }}"
                 alt="Card image cap"/>
            <div class="card-body">
              <p class="card-text">Товар: {{ object.product_name }}</p>
              <p class="card-text">Описание: {{ object.description_prod|slice:100}}</p>
              <p class="card-text">Цена: {{ object.purchase_price }} руб.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Купить</button>
                 <a <button type="button" class="btn btn-sm btn-outline-success" href="{% url 'catalog:product' object.pk %}">Просмотр товара</button></a>
                    {% if perms.catalog.change_product and user == object.owner %}
                    <a <button type="button" class="btn btn-sm btn-outline-info" href="{% url 'catalog:update_product' object.pk %}">Изменить</button></a>
                    {% endif %}
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
           {% endif %}
          {% endfor %}
    {% endif %}
  </div>
      {% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  <div class="col">
          <div class="card shadow-sm">
            <img class="card-img-top"
                 data-crs = "{{ object.picture|media }}"
                 alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Товар: {{ object.product_name }} </p>
              <p class="card-text">Описание: {{ object.description_prod }}</p>
              <p class="card-text">Цена: {{ object.purchase_price }} руб.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Купить</button>
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
      <div class="col-12">
          <div class="row">
           <div class="card col-6">
               <div class="card-header">
                   <h3 class="card-title"></h3>
                   {% if object %}
                   Создать изменения
                   {% else %}
                      Добавление продукта
                   {% endif %}
                       <div class="card-body">
                         <form method="post" enctype="multipart/form-data">
                           {% csrf_token %}
                           {{ form.as_p }}
                           <button type="submit" class="btn btn-success">
                           {% if object %}
                            Сохранить изменения
                           {% else %}
                            Создать</button>
                           {% endif %}
                       </div>
                   </div>
               </div>
            <div class="col-6">
                <div class="card">
                   <div class="card-header">
                   <h3 class="card-title"></h3>
                    Версия продукта
                      <div class="card-body">
                     {{ formset.management_form}}
                     {% for form in formset.forms %}
                     {{ form.as_p }}
                       {% if not forloop.last %}
                            <hr>
                        {% endif %}
                     {% endfor %}
                         </div>
                </div>
          </div>
        </div>
       </form>
   </div>
 </div>

{% endblock %}